// Generated by CoffeeScript 2.7.0
var Background, Hello, Hero, Markdown, body;

import m from "https://cdn.skypack.dev/mithril";

import * as commonmark from "https://cdn.skypack.dev/commonmark";

// TODO: sensible default style
document.head.innerHTML += `<link 
  rel="preconnect" 
  href="https://fonts.googleapis.com">
<link 
  rel="preconnect" 
  href="https://fonts.gstatic.com" 
  crossorigin>
<link 
  rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700&display=swap"> `;

document.head.innerHTML += `<style> 
* {
  margin: 0;
  padding: 0;
}
</style>`;

Hello = class Hello {
  oninit(vnode) {
    return this.count = 0;
  }

  view(vnode) {
    var state;
    state = vnode.state;
    return m("main", [
      m("h1",
      {
        class: "title"
      },
      "My first zapp",
      m("button",
      {
        onclick: (() => {
          return this.count++;
        })
      },
      this.count + " clicks"))
    ]);
  }

};

Background = class Background {
  view(vnode) {
    var attrs, children, url;
    ({attrs, children} = vnode);
    console.log(attrs, children);
    ({url} = attrs);
    return m("div", {
      style: {
        width: "100vw",
        height: "100vh",
        backgroundImage: `url('${url}')`,
        backgroundSize: "cover"
      }
    }, children);
  }

};

Hero = class Hero {
  view(vnode) {
    return m("div", {
      style: {
        width: "100vw",
        height: "100vh",
        backgroundColor: "#c8d8e4",
        display: "flex",
        alignItems: "center",
        justifyContent: "center"
      }
    }, m("h1", {
      style: {
        fontFamily: "Rubik",
        fontSize: "192px"
      }
    }, vnode.children));
  }

};

Markdown = class Markdown {
  view(vnode) {
    var ast, attrs, children, html, reader, text, writer;
    ({attrs, children} = vnode);
    ({text} = attrs);
    reader = new commonmark.Parser();
    writer = new commonmark.HtmlRenderer();
    ast = reader.parse(text);
    html = writer.render(ast);
    return m.trust(html);
  }

};

body = document.body;

// m.mount(body, view: -> m Hero, "Back Deck")
m.route(body, "/splash", {
  "/splash": {
    view: function() {
      return m(Hero, [
        "Back Deck",
        m("a",
        {
          href: "#!hello"
        },
        "👋"),
        m("a",
        {
          href: "#!pencil"
        },
        "✏️"),
        m("a",
        {
          href: "#!markdown"
        },
        "📄")
      ]);
    }
  },
  "/hello": {
    view: function() {
      return m(Hero, "👋 Hello!");
    }
  },
  "/pencil": {
    view: function() {
      return m(Background, {
        url: "images/joanna-kosinska-1_CMoFsPfso-unsplash.jpg"
      });
    }
  },
  "/markdown": {
    view: function() {
      return m(Markdown, {
        text: `Title
=====

Buh

- I can't do that **Dave**!

-----

[Le Monde](https://www.lemonde.fr)
`
      });
    }
  }
});
